version: "3.8"

services:
  backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: backend
      args:
        - PORT=${PORT}
    command: "uvicorn main:app --host 0.0.0.0 --port ${PORT} --log-level info --log-config logging.conf"
    ports:
    - "${PORT}:${PORT}"
    env_file:
      - ./.env
    networks:
      backend:


  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: